version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: lh_nauticals
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: